project_id = "jzgzdypwcohwxpbzhhtw"

[functions.admin-manage-users]
verify_jwt = false

[functions.analyze-product-image]
verify_jwt = true

[functions.analyze-tray]
verify_jwt = true

[functions.process-analysis-queue]
verify_jwt = false

[functions.send-push]
verify_jwt = false
